### ISSUE TITLE
sdl-library-init and .so filename

### ISSUE THREAD

**Issue by weinholt** [ovenpasta/thunderchez#1]
I'm trying (sdl2) on Debian 8.6 and got this error:

<pre>
> (import (sdl2))
> (sdl-library-init)
Exception: (while loading libSDL2.so) libSDL2.so: cannot open shared object file: No such file or directory
Type (debug) to enter the debugger.
</pre>

In some sense it's my own fault. In Debian the file "libSDL2.so" is in libsdl2-dev. But the package libsdl2-2.0-0 has "libSDL2-2.0.so.0", which seems to work perfectly well with the ffi. I think it would be a good thing if the (sdl2) library could work without the -dev package being installed.

I would have just passed the other filename to sdl-library-init myself, but I think there's a bug in that procedure. It looks like it's made to take an alternative filename as an argument, but in that case it passes a list to load-shared-object.

**Comment by ovenpasta** [comment]
Hi, You're right, I've just fixed that.... thank you. 
I think there is no easy way to determine which version of the shared library is installed without the dev package... I'll try to figure out the best way to find it or maybe let the user specify it directly (as with the fix).
Also... did you take a look at the fossil repository? I'm actually commiting changes there

Here's the fix...
https://pizzahack.eu/fossil/thunderchez/fdiff?sbs=1&v1=7de285e409eff8dd&v2=9164e688a1f46e88

Also you can find an example of the sdl2 library here:
https://pizzahack.eu/fossil/miogui

**Comment by weinholt** [comment]
Cool, thanks!
